# Generated by Django 3.2.2 on 2021-11-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_studdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studdata',
            name='FEcgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studdata',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
