# Generated by Django 3.2.2 on 2021-11-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211121_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studdata',
            name='dateofbirth',
        ),
    ]
